# Generated by Django 6.0.1 on 2026-01-16 10:20

import django.db.models.deletion
import django_summernote.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the news article', max_length=300)),
                ('slug', models.SlugField(help_text='SEO-friendly slug for the article', unique=True)),
                ('content', django_summernote.fields.SummernoteTextField(help_text='Content of the news article')),
                ('excerpt', models.TextField(help_text='Brief excerpt of the article for list views')),
                ('featured_image', models.ImageField(help_text='Featured image for the article (used in detail view)', upload_to='news/featured/')),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Thumbnail image for the article (used in list views, auto-generated if not provided)', null=True, upload_to='news/thumbnails/')),
                ('author_name', models.CharField(help_text='Name of the author', max_length=200)),
                ('author_title', models.CharField(blank=True, help_text='Title of the author', max_length=300)),
                ('publish_date', models.DateTimeField(help_text='Date when the article should be published')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published')], default='draft', help_text='Status of the article in the publishing workflow', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this article is featured on homepage')),
                ('tags', taggit.managers.TaggableManager(help_text='Tags for the article (comma separated)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the news category', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='SEO-friendly slug for the category', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the category')),
                ('icon_image', models.ImageField(blank=True, help_text='Icon image for the category', null=True, upload_to='news/category_icons/')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('newsarticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.newsarticle')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('location', models.CharField(help_text='Location of the event', max_length=300)),
                ('registration_link', models.URLField(blank=True, help_text='Registration link for the event (optional)')),
                ('event_image', models.ImageField(blank=True, help_text='Specific image for the event (if different from news featured image)', null=True, upload_to='events/')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date', '-publish_date'],
            },
            bases=('news.newsarticle',),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the news article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newscategory'),
        ),
    ]
