# Generated by Django 6.0.1 on 2026-01-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('governance', 'Governance'), ('programmes', 'Academic Programmes'), ('programme-detail', 'Programme Detail'), ('library', 'Library'), ('student-life', 'Student Life'), ('recreation', 'Recreation'), ('research', 'Research'), ('news-events', 'News & Events'), ('contact', 'Contact Us')], help_text='Unique identifier for the page', max_length=20, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional overlay title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional overlay subtitle', max_length=300)),
                ('background_image', models.ImageField(help_text='Hero image for the page navbar/hero section', upload_to='heroes/')),
                ('overlay_opacity', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100)], default=50, help_text='Opacity percentage for dark overlay (0-100)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this hero is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Hero',
                'verbose_name_plural': 'Page Heroes',
                'ordering': ['page_identifier'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='National Intelligence and Research University', max_length=200)),
                ('short_name', models.CharField(default='NIRU', max_length=20)),
                ('tagline', models.CharField(default='Premier Science and Research-Intensive African University', max_length=200)),
                ('address', models.TextField(default='P.O. Box 47446 - 00100, Nairobi, Kenya')),
                ('phone_numbers', models.JSONField(default=list, help_text='List of phone numbers')),
                ('email', models.EmailField(default='admin@niru.ac.ke', max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('copyright_text', models.TextField(default='Copyright 2025. National Intelligence and Research University. All Rights Reserved.')),
                ('charter_date', models.DateField(blank=True, null=True)),
                ('charter_by', models.CharField(blank=True, help_text='Who chartered the university', max_length=200)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('analytics_code', models.TextField(blank=True, help_text='Google Analytics or other tracking code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
