# Generated by Django 6.0.1 on 2026-01-16 08:23

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', django_summernote.fields.SummernoteTextField(help_text='Mission statement with rich text formatting')),
                ('vision', django_summernote.fields.SummernoteTextField(help_text='Vision statement with rich text formatting')),
                ('history', django_summernote.fields.SummernoteTextField(help_text='History of the university with rich text formatting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the core value', max_length=200)),
                ('icon', models.ImageField(blank=True, help_text='Icon image for the core value', null=True, upload_to='core_values/')),
                ('description', models.TextField(help_text='Description of the core value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
            },
        ),
        migrations.CreateModel(
            name='ViceChancellorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the Vice Chancellor', max_length=200)),
                ('title', models.CharField(help_text='Title and credentials', max_length=300)),
                ('photo', models.ImageField(help_text='Photo of the Vice Chancellor', upload_to='vc_photos/')),
                ('message', django_summernote.fields.SummernoteTextField(help_text='Message from the Vice Chancellor')),
                ('signature', models.ImageField(blank=True, help_text='Signature image of the Vice Chancellor', null=True, upload_to='vc_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vice Chancellor Message',
                'verbose_name_plural': 'Vice Chancellor Messages',
            },
        ),
    ]
