# Generated by Django 6.0.1 on 2026-01-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_emails', models.TextField(help_text='Comma-separated list of email addresses to receive contact form submissions')),
                ('auto_reply_enabled', models.BooleanField(default=True, help_text='Whether to send an auto-reply to the submitter')),
                ('auto_reply_subject', models.CharField(default='Thank you for contacting us', help_text='Subject for the auto-reply email', max_length=300)),
                ('auto_reply_message', models.TextField(help_text="Template for the auto-reply message (use {name} for submitter's name)")),
                ('success_message', models.TextField(default='Thank you for your message. We will get back to you soon.', help_text='Message to display after successful submission')),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the person submitting the form', max_length=200)),
                ('email', models.EmailField(help_text='Email address of the submitter', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the submitter', max_length=20)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=300)),
                ('message', models.TextField(help_text='Content of the message')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the submitter (captured automatically)')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the submission has been read by admin')),
                ('replied_at', models.DateTimeField(blank=True, help_text='Date and time when the submission was replied to', null=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
