# Generated by Django 6.0.1 on 2026-01-16 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the facility', max_length=200)),
                ('image', models.ImageField(help_text='Image of the facility', upload_to='facilities/')),
                ('description', models.TextField(help_text='Description of the facility')),
                ('category', models.CharField(choices=[('recreation', 'Recreation'), ('accommodation', 'Accommodation'), ('dining', 'Dining'), ('study', 'Study'), ('other', 'Other')], help_text='Category of the facility', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service', max_length=200)),
                ('image', models.ImageField(help_text='Image of the service', upload_to='services/')),
                ('description', models.TextField(help_text='Description of the service')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the service should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecreationFacility',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_life.facility')),
                ('capacity', models.CharField(blank=True, help_text='Capacity of the facility', max_length=100)),
                ('availability', models.CharField(blank=True, help_text='Availability schedule', max_length=200)),
                ('equipment_available', models.TextField(blank=True, help_text='List of equipment available')),
                ('rules_regulations', models.TextField(blank=True, help_text='Rules and regulations for the facility')),
            ],
            options={
                'verbose_name': 'Recreation Facility',
                'verbose_name_plural': 'Recreation Facilities',
            },
            bases=('student_life.facility',),
        ),
    ]
