# Generated by Django 6.0.1 on 2026-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the Board Member', max_length=200)),
                ('position', models.CharField(help_text='Position in the board', max_length=300)),
                ('photo', models.ImageField(help_text='Photo of the Board Member', upload_to='governance/members/')),
                ('bio', models.TextField(blank=True, help_text='Biography of the Board Member')),
                ('board_type', models.CharField(choices=[('trustees', 'Board of Trustees'), ('council', 'University Council'), ('senate', 'University Senate'), ('management', 'Management Board')], help_text='Type of board the member belongs to', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
                'ordering': ['board_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chancellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the Chancellor', max_length=200)),
                ('title', models.CharField(help_text='Title and credentials', max_length=300)),
                ('credentials', models.CharField(blank=True, help_text='Additional credentials (e.g., PhD, C.G.H)', max_length=200)),
                ('photo', models.ImageField(help_text='Photo of the Chancellor', upload_to='governance/chancellor/')),
                ('description', models.TextField(blank=True, help_text='Description or biography of the Chancellor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chancellor',
                'verbose_name_plural': 'Chancellors',
            },
        ),
        migrations.CreateModel(
            name='GovernanceBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('trustees', 'Board of Trustees'), ('council', 'University Council'), ('senate', 'University Senate'), ('management', 'Management Board')], help_text='Name/type of the governance body', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of the governance body')),
                ('image', models.ImageField(help_text='Image representing the governance body (e.g., meeting photo)', upload_to='governance/body_images/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which this body should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Members of this governance body', to='governance.boardmember')),
            ],
            options={
                'verbose_name': 'Governance Body',
                'verbose_name_plural': 'Governance Bodies',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
