# Generated by Django 6.0.1 on 2026-01-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the newsletter issue', max_length=300)),
                ('content', models.TextField(help_text='Content of the newsletter issue')),
                ('issue_number', models.PositiveIntegerField(help_text='Sequential issue number')),
                ('sent_date', models.DateTimeField(blank=True, help_text='Date when the newsletter was sent', null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0, help_text='Number of recipients the newsletter was sent to')),
            ],
            options={
                'verbose_name': 'Newsletter Issue',
                'verbose_name_plural': 'Newsletter Issues',
                'ordering': ['-issue_number'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email address of the subscriber', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Name of the subscriber', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscriber is active')),
                ('subscribed_date', models.DateTimeField(auto_now_add=True, help_text='Date when the user subscribed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the user subscribed', null=True)),
                ('unsubscribe_token', models.CharField(help_text='Token for unsubscribe functionality', max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-subscribed_date'],
            },
        ),
    ]
