# Generated by Django 6.0.1 on 2026-01-16 08:23

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the programme', max_length=300)),
                ('code', models.CharField(help_text='Programme code (e.g., MISPS, MSIS)', max_length=20, unique=True)),
                ('slug', models.SlugField(help_text='SEO-friendly slug for the programme', unique=True)),
                ('description', django_summernote.fields.SummernoteTextField(help_text='Detailed description of the programme')),
                ('duration', models.CharField(help_text='Duration of the programme (e.g., 2 years)', max_length=100)),
                ('mode', models.CharField(help_text='Mode of study (e.g., Full-time / Part-time)', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline for the programme', max_length=500)),
                ('full_description', django_summernote.fields.SummernoteTextField(blank=True, help_text='Extended description of the programme')),
                ('admission_requirements_description', models.TextField(help_text='General admission requirements description for the programme')),
                ('application_note', models.TextField(blank=True, help_text='Application note or instructions')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this programme is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(help_text='Specific admission requirement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_reqs', to='academics.programme')),
            ],
            options={
                'verbose_name': 'Admission Requirement',
                'verbose_name_plural': 'Admission Requirements',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the highlight', max_length=200)),
                ('icon', models.ImageField(blank=True, help_text='Icon image for the highlight', null=True, upload_to='programme_highlights/')),
                ('description', models.TextField(help_text='Description of the highlight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='academics.programme')),
            ],
            options={
                'verbose_name': 'Programme Highlight',
                'verbose_name_plural': 'Programme Highlights',
            },
        ),
    ]
